[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#1a163a"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false